
- name: install dependencies
  package:
    name: apache2
    state: present

- name: enable expires module
  apache2_module:
    state: present
    name: expires
  notify: reload webserver

- name: enable headers module
  apache2_module:
    state: present
    name: headers
  notify: reload webserver

- name: set expires conf file
  copy:
    src: expires.conf
    dest: /etc/apache2/mods-available/expires.conf
  notify: reload webserver

- name: "Create symlink to the mods enabled for expires.conf"
  file:
    dest: /etc/apache2/mods-enabled/expires.conf
    src: /etc/apache2/mods-available/expires.conf
    state: link
  notify: reload webserver

- name: make sure unzip is installed
  apt:
    name: unzip

- name: empty folder
  file:
    state: absent
    path: /var/www/html

- name: recreate it
  file:
    state: directory
    path: /var/www/html
    owner: www-data

- name: "Set owner www-data on /var/www/html"
  file:
    dest: /var/www/html
    owner: www-data
    group: www-data
    mode: 0744
    recurse: yes

- name: "Create config file for apache"
  template:
    src: 000-default.conf
    dest: /etc/apache2/sites-available/000-default.conf
    mode: 0644
  notify: reload webserver

- include_tasks: segments.yml

